name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  cloud_firestore: 4.2.0
  cloud_firestore_platform_interface: 5.9.1
  cloud_firestore_web: 3.1.1
  cloud_functions: 4.0.6
  cloud_functions_platform_interface: 5.1.25
  cloud_functions_web: 4.3.14
  firebase_auth: 4.2.0
  firebase_auth_platform_interface: 6.11.4
  firebase_auth_web: 5.2.0
  firebase_core: 2.4.0
  firebase_core_platform_interface: 4.5.2
  firebase_core_web: 2.0.2
  firebase_messaging: 14.1.4
  firebase_messaging_platform_interface: 4.2.8
  firebase_messaging_web: 3.2.9
  firebase_storage: 11.0.7
  firebase_storage_platform_interface: 4.1.25
  firebase_storage_web: 3.3.17

  supabase: 1.6.3
  supabase_flutter: 1.7.0

  fireflow:
    path: ..

  go_router:
  rxdart: 0.27.4

  flutterflow_widgets: ^0.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  rxdart: 0.27.4

flutter:
  uses-material-design: true

  #
