name: fireflow
description: This package is designed for FlutterFlow app to provide enhanced features.
version: 0.0.48
homepage: https://github.com/withcenter/fireflow

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: 4.2.0
  cloud_firestore_platform_interface: 5.9.1
  cloud_firestore_web: 3.1.1
  cloud_functions: 4.0.6
  cloud_functions_platform_interface: 5.1.25
  cloud_functions_web: 4.3.14
  firebase_auth: 4.2.0
  firebase_auth_platform_interface: 6.11.4
  firebase_auth_web: 5.2.0
  firebase_core: 2.4.0
  firebase_core_platform_interface: 4.5.2
  firebase_core_web: 2.0.2
  firebase_messaging: 14.1.4
  firebase_messaging_platform_interface: 4.2.8
  firebase_messaging_web: 3.2.9
  firebase_storage: 11.0.7
  firebase_storage_platform_interface: 4.1.25
  firebase_storage_web: 3.3.17

  image_picker: 0.8.5+3
  image_picker_android: 0.8.5+3
  image_picker_for_web: 2.1.10
  image_picker_ios: 0.8.6+1
  image_picker_platform_interface: 2.6.2

  mime_type: 1.0.0
  chewie: 1.3.4

  video_player: 2.4.5
  video_player_android: 2.3.8
  video_player_avfoundation: 2.3.5
  video_player_platform_interface: 5.1.3
  video_player_web: 2.0.12

  path: 1.8.2
  flutterflow_paginate_firestore: ^1.0.3+1

  file_picker: 4.5.1
  cached_network_image: 3.2.1

  http: ^0.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
