name: fireflow
description: This package is designed for FlutterFlow app to provide enhanced features.
version: 0.0.1
homepage: https://github.com/withcenter/fireflow

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
