name: fireflow
description: This package is designed for FlutterFlow app to provide enhanced features.
version: 0.1.0
homepage: https://github.com/withcenter/fireflow

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  built_collection: 5.1.1
  built_value: 8.4.0

  cached_network_image: 3.2.1
  cloud_firestore: 4.2.0
  cloud_firestore_platform_interface: 5.9.1
  cloud_firestore_web: 3.1.1
  cloud_functions: 4.0.6
  cloud_functions_platform_interface: 5.1.25
  cloud_functions_web: 4.3.14
  file_picker: 4.5.1
  firebase_auth: 4.2.0
  firebase_auth_platform_interface: 6.11.4
  firebase_auth_web: 5.2.0
  firebase_core: 2.4.0
  firebase_core_platform_interface: 4.5.2
  firebase_core_web: 2.0.2
  firebase_messaging: 14.1.4
  firebase_messaging_platform_interface: 4.2.8
  firebase_messaging_web: 3.2.9
  firebase_storage: 11.0.7
  firebase_storage_platform_interface: 4.1.25
  firebase_storage_web: 3.3.17

  firebase_ui_firestore: 1.1.1

  # for file upload
  image_picker: 0.8.5+3
  image_picker_android: 0.8.5+3
  image_picker_for_web: 2.1.10
  image_picker_ios: 0.8.6+1
  image_picker_platform_interface: 2.6.2

  # for json serialization
  json_annotation: 4.8.0
  json_serializable: 6.6.1

  mime_type: 1.0.0
  # chewie: 1.3.4

  # video_player: 2.4.5
  # video_player_android: 2.3.8
  # video_player_avfoundation: 2.3.5
  # video_player_platform_interface: 5.1.3
  # video_player_web: 2.0.12

  path: 1.8.2

  http: ^0.13.5

  # used in serialization
  from_css_color: 2.0.0

  # push notification
  another_flushbar: ^1.12.29

  supabase: 1.2.0
  supabase_flutter: 1.2.2

  # supabase 1.2.0 depends on rxdart ^0.27.5
  # fireflow depends on rxdart 0.27.4 and it overrides.
  rxdart: 0.27.5

  #
  easy_debounce: 2.0.1

  # Saving data locally. Used in chat service.
  # shared_preferences: 2.0.15

  # 최신 Firebase SDK 를 지원하는 firestore pagination 위젯
  flutterflow_paginate_firestore: ^1.0.3+1

  # 직접 작성한 플러터플로 위젯 모음
  flutterflow_widgets: ^0.0.42

  # google map
  # google_maps: 6.2.0
  # google_maps_flutter: 2.1.8
  # google_maps_flutter_platform_interface: 2.2.1
  # google_maps_flutter_web: 0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.3.3
  built_value_generator: ^8.4.4

  # Because the version of fake_cloud_firestore (18 days ago from Jan 29, 2023) depense on fake_firebase_security_rules that depense on Dart SDK 2.18.6, the depency fails.
  # Because the version of fake_cloud_firestore (25 days ago from Jan 29, 2023) depense on mock_exceptions that depense on Dart SDK 2.18.6, the depency fails.
  #
  fake_cloud_firestore: ^2.1.0
  # firebase_auth_mocks: ^0.10.3

dependency_overrides:
  # rxdart: 0.27.4 # Don't overrides non-dev packages.
  # This is for firebase_auth_mocks. If it produces problem on deploying, remove it.
  # firebase_auth_platform_interface: 6.11.4

flutter:
