// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqitIPdEOcTznjK-EIHCeqLD-HYKzaaCU',
    appId: '1:1091153425562:web:c3505ccab57bcf12fa9b23',
    messagingSenderId: '1091153425562',
    projectId: 'withcenter-fireflow',
    authDomain: 'withcenter-fireflow.firebaseapp.com',
    storageBucket: 'withcenter-fireflow.appspot.com',
    measurementId: 'G-KXG98TD4LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALWCc85GW7FeB7sCOEjgncIiiwzzFf7-Y',
    appId: '1:1091153425562:android:d7493b3caef95ac4fa9b23',
    messagingSenderId: '1091153425562',
    projectId: 'withcenter-fireflow',
    storageBucket: 'withcenter-fireflow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUAzX_uOE0MiPVrHOX-uU15C9ZBkJXVvU',
    appId: '1:1091153425562:ios:9ce15fa0ffdcce44fa9b23',
    messagingSenderId: '1091153425562',
    projectId: 'withcenter-fireflow',
    storageBucket: 'withcenter-fireflow.appspot.com',
    androidClientId:
        '1091153425562-k902fmdi7bfrg0hh3euhgftholdoj086.apps.googleusercontent.com',
    iosClientId:
        '1091153425562-g8rs75stp6aeoisf6ci0froob43jrq9t.apps.googleusercontent.com',
    iosBundleId: 'com.fireflow.ex',
  );
}
